### PR TITLE
Server support

### PR DESCRIPTION
**Pull request by robotbrain**

### CODE REVIEW

**Comment by 02JanDal** [comment]
Well to begin with this won't be written to the files (need to add stuff in `reader_writer.rb`).

Apart from that I believe this won't be so easy. The server download seems to include all dependencies, thus they shouldn't be included if it's a server.

I guess the main question is do we want per-resource or per-patch sidedness? Maybe have it per-patch in the root object (`"side": "{both,server,client}"`) and include it in the version index, and then say that different versions with different sidedness are distinct? I'd prefer to wait with deciding this, but since you need it for your project some temporary solution could be put in place.

@peterix thoughts?

**Comment by peterix** [comment]
The set of libraries, mods and coremods and their config files likely can have client/server side.

Take a look at this thing:
http://wiki.sk89q.com/wiki/Launcher/Package_creation#Mixing_server_and_client_files

We do not allow custom jars, because there are jar mods for that, it doesn't understand the client/server sidedness for libraries on that level.

Without forge, the minecraft server doesn't seem to have any external dependencies and it downloads/creates the things it needs.

Take a look at this second thing:
https://gist.github.com/peterix/3bfb49fe4bdc1be558c5

You can see the 'serverreq' and 'clientreq' attributes. Those are rules in disguise! 
'clientreq' seems to be a hint for the installer that it should fetch this library when creating the client profile.
'serverreq' is the same, but for the server side.

Because there is no installer, we need to have 'server side' for libraries too, or install all of the libraries.

**Comment by peterix** [comment]
Can we run into problems when the server has more libraries than it needs?

**Comment by 02JanDal** [comment]
Problems should only arise if libraries with different versions overlap (in which case I can imagine quite bad problems as a result).

I too dislike the `serverreq` and `clientreq` stuff, and even after going through the official installers source several times I still don't understand what they do (to the extent that I don't understand how it manages to work at all...).

Another question: Are the three sides (both, server, client) enough? Are there other things that fit into the same that we might want to add in the future? The answer to this could affect the decision of what to do.

**Comment by peterix** [comment]
In the existing formats, the defaults for them are different.

For mods, it's 'both'.
For libraries, it seems to be 'client'.

This is weird and inconsistent

**Comment by peterix** [comment]
The 'sides' should be done in a way that allows us to extend them later. Can you think of a thing with 3? Suddenly you have an explosion of states.

**Comment by peterix** [comment]
```
sides : ['client','server'],
```

**Comment by 02JanDal** [comment]
Yep. Next question would be where to have that? Per-patch and have different patches per side? Or per-resource (that is: per-library/per-mod/etc.)?

**Comment by peterix** [comment]
I would say per-resource, where it makes sense. You can then add a mod, and not care where it goes, or look for the server side of it, if it is split.

**Comment by 02JanDal** [comment]
That works for array resources (like libraries) but not really for single-string resources (like mainClass, which is different between the Minecraft client and server). Maybe something like this then?

```json
"mainClass": {
    "client": "...",
    "server": "..."
}
```

It feels like that makes it a lot more complicated though.

**Comment by peterix** [comment]
Can it have a different main class?

What the real issue is ... we have only minecraft to look at.

It seems to be just 'java  -XSOME_JAVA_PARAMS -jar mcserver.jar'

**Comment by peterix** [comment]
Also: forge has a different main jar for the server, but it still needs the mc server jar, in the same folder.

It is 'special'.

**Comment by 02JanDal** [comment]
So the main remaining issue I think (after that we should be able to model most cases) is how to define sidedness for non-array resources.

For the forge server the patch would override the mainJar and then maybe have the mc server jar as a normal file download?

**Comment by 02JanDal** [comment]
http://www.reddit.com/r/VoxelGameDev/comments/why8x/the_big_list_of_block_engines/

Ultimately, we should be able to support all of these (if we can do that we should be able to support any game out there). I guess we could start to look at terasology (also java) to get a bit more of a perspective.

**Comment by peterix** [comment]
Notice that this ultimately forms a 'template' (avoiding the term 'modpack'), that should be the same for every 'side'.

**Comment by 02JanDal** [comment]
Terasology seems to be the same for server and client, but adding `-headless` to the command line. So this further means we need a way to define sidedness for strings.

**Comment by peterix** [comment]
Or 'launch methods'. Basically the side, but fleshed out.

**Comment by peterix** [comment]
Funny thing: a mod can then define its own launch method :P *SO SPECIAL*

**Comment by 02JanDal** [comment]
So far we don't have any resources that are an object (only arrays and strings). **IF** we can assume that we will never have a resource that's an object (or alternatively say that they have to be in a single-element array) we could say
```json
"resourceKeyA": <normal resource>,
"resourceKeyB": {
    "client": <normal resource for client>,
    "server": <normal resource for server>
}
```
So the parser would look if the resource is an object. If it is, chooses the correct side. Implementation detail: we could end up with something like this: `QJsonValue getResource(const QString &key, const QString side)` and the rest would be transparent (object: return the right value, non-object: just return it).

For resources that want it (libraries for example) they could then themselves handle per-item sides.

**Comment by peterix** [comment]
I'm not sure about that one. What I had in mind is this:
instead of stuffing resources into ever smaller boxes, some of the related ones could be grouped.
The above also relies on the details of the json format for meaning and is limiting.

See, a game entry for Minecraft 1.5.2:
```
{
  "formatVersion": 0,
  "uid": "net.minecraft",
  "version": "1.5.2",
  "time": 1366904700,
  "type": "release",
  "data": {
    "general.traits": [
      "legacyLaunch",
      "texturepacks"
    ],
    "general.launcher": "minecraft",
    "java.mainLib": {
      "name": "net.minecraft:minecraft:1.5.2",
      "absoluteUrl": "http://s3.amazonaws.com/Minecraft.Download/versions/1.5.2/1.5.2.jar"
    },
    "mc.arguments": " ${auth_player_name} ${auth_session}"
  }
}
```

The hacks present: `general.traits` and `general.launcher` Why?
* `texturepacks` is a folder resource.
* `legacyLaunch` is a launch method and specific to multimc
* `general.launcher` is just a copy of the above, exhibiting the same problems that any copypasta has: it got out of sync almost immediately.

What does constitute a launch method?
The parts that put together the command line arguments for the launch and the actions taken during launch. It's code. What MultiMC does is implement the launch via the 'launcher part', which is as MultiMC-specific as it gets. We do not have a classpath argument, the main jar is 'NewLaunch.jar', and the 'other main jar' is there so we can be sure it's inserted - **by code** - at the right point, and that it is post-processed - **by yet more code** - to include special jar mod resources.

I would also assume other launchers would use different launch methods, or even defer to the mojang launcher and decide to rewrite this format into the vanilla one.

The difference between 'legacyLaunch' and the normal launch is us applying reflection hacks to make the old versions run.

Questions/conclusions:
* `legacyLaunch` and `general.launcher`
* How do we encode that running a server with forge needs to run a different jar, with the mojang one still present?
* I'd say resources that need to vary between launch methods should explicitly define that. I'd settle for `side: ["server", "client", "etc."]`
* Even Minecraft has *many* different variants of servers. Do we want to encode the differences? Would that help? Bukkit? The successor of bukkit? The oddball ones? Is it worth it?

Ultimately, we need to draw a line somewhere and stop. See: http://en.wikipedia.org/wiki/Analysis_paralysis

**Comment by robotbrain** [comment]
bukkit, the successor thereof, etc USUALLY are a replacement server jar

**Comment by peterix** [comment]
So, forge is being special?

**Comment by robotbrain** [comment]
forge is a replacement server jar with a special library

**Comment by peterix** [comment]
Can we possibly make it load the library from a different path? Like the library folder? That would fit into the pattern.

**Comment by peterix** [comment]
From a forge jar:
```
Manifest-Version: 1.0
TweakClass: net.minecraftforge.fml.common.launcher.FMLTweaker
Class-Path: libraries/net/minecraft/launchwrapper/1.11/launchwrapper-1
 .11.jar libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar librari
 es/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar 
 libraries/com/typesafe/config/1.2.1/config-1.2.1.jar libraries/org/sc
 ala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.1
 1-1.1.0.jar libraries/org/scala-lang/scala-compiler/2.11.1/scala-comp
 iler-2.11.1.jar libraries/org/scala-lang/plugins/scala-continuations-
 library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar librari
 es/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/sca
 la-continuations-plugin_2.11.1-1.0.2.jar libraries/org/scala-lang/sca
 la-library/2.11.1/scala-library-2.11.1.jar libraries/org/scala-lang/s
 cala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.
 1.jar libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.1
 1.1.jar libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2
 .11-1.0.1.jar libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml
 _2.11-1.0.2.jar libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar libraries/ne
 t/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar minecraft_server
 .1.8.jar
Main-Class: net.minecraftforge.fml.relauncher.ServerLaunchWrapper
```

This means that we can ignore this and specify the classpath and main class ourselves. The original mc server becomes a library, like any other library.

**Comment by peterix** [comment]
The other topics should be moved to a separate issue. I think this is viable, and good enough for now.

**Pull request merged**
